server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/log_analysis?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

bigdata:
  kafka:
    bootstrap-servers: 192.168.146.128:9092
    topic: log-topic
    group-id: log-analysis-group
  flink:
    enabled: true
    rest-address: 192.168.146.128
    rest-port: 8081
  hdfs:
    uri: hdfs://192.168.146.128:9000
    user: root
