agent.sources = http-source
agent.sinks = kafka-sink
agent.channels = memory-channel

agent.sources.http-source.type = http
agent.sources.http-source.port = 44444
agent.sources.http-source.handler = org.apache.flume.source.http.JSONHandler
agent.sources.http-source.channels = memory-channel

agent.sinks.kafka-sink.type = org.apache.flume.sink.kafka.KafkaSink
agent.sinks.kafka-sink.kafka.bootstrap.servers = 192.168.146.128:9092
agent.sinks.kafka-sink.kafka.topic = log-topic
agent.sinks.kafka-sink.kafka.producer.acks = 1

agent.channels.memory-channel.type = memory
agent.channels.memory-channel.capacity = 1000
agent.channels.memory-channel.transactionCapacity = 100

agent.sources.http-source.channels = memory-channel
agent.sinks.kafka-sink.channel = memory-channel
